### PR TITLE
Bugfix/227 fix current time on steam not updating

### LINKED ISSUE #227: [Must Have] - Current time on Steam taking too long to update
When playing a level, the current time status on Steam takes way too long to update. I believe this is because requests are being made to the Steam API every frame, and needs to be completely reduced to every 1 or 2 seconds.

Steps to reproduce:
1. Start up the game.
2. Play any level.
3. Compare your current time in the game versus on Steam.

A/C:
1. Requests to the Steam API to update the current time should only be done every 1 second or 2, as opposed to every frame.
2. [Optional] Implemented the ability to programmatically change the time it takes to send a request to the Steam API.

### PR DESCRIPTION
**Pull request by AlphaPromethium**
Closes #227.

This fixes the current time on Steam not updating by adding an X second timer between the next call to the Steam API, where the value of X can be changed in the code.

The reason for the timer not updating on Steam is because the game is sending requests to the Steam API every frame, which is way too quick.

~~**_This PR should only be merged when #221 gets merged and when I resolve merge conflicts here, but I still want to get an approval for the time being!_**~~

### CODE REVIEW

File: src/SSVOpenHexagon/Core/HGUpdate.cpp [hunk 1]
```diff
@@ -27,9 +27,18 @@ void HexagonGame::update(ssvu::FT mFT)
 
     // TODO: refactor to avoid repetition, and truncate floating point number
     // TODO: also show best record (here) and last run + best record (in menu)
-    steamManager.set_rich_presence_in_game(
-        levelData->name, status.getTimeSeconds());
-    steamManager.run_callbacks();
+
+    const int DELAY_TO_UPDATE = 5; // X seconds
```
Comment (SuperV1234) [inline src/SSVOpenHexagon/Core/HGUpdate.cpp:31]:
```suggestion
    constexpr float DELAY_TO_UPDATE = 5; // X seconds
```

Make this `constexpr` (minor change, it means it's a compile-time constant) and `float` so it matches the type we're trying to compare against.

File: src/SSVOpenHexagon/Core/HGUpdate.cpp [hunk 2]
```diff
@@ -27,9 +27,18 @@ void HexagonGame::update(ssvu::FT mFT)
...
+    static float timeTillUpdate = 0.0;
```
Comment (SuperV1234) [inline src/SSVOpenHexagon/Core/HGUpdate.cpp:32]: This should be a data member of `HexagonGame` rather than a `static` variable. How about also calling it `timeUntilRichPresenceUpdate`?

File: src/SSVOpenHexagon/Core/HGUpdate.cpp [hunk 3]
```diff
@@ -27,9 +27,18 @@ void HexagonGame::update(ssvu::FT mFT)
...
+    timeTillUpdate -= mFT / 60.0;
```
Comment (SuperV1234) [inline src/SSVOpenHexagon/Core/HGUpdate.cpp:33]:
```suggestion
    timeTillUpdate -= ssvu::getFTToSeconds(mFT);
```

File: src/SSVOpenHexagon/Core/HGUpdate.cpp [hunk 4]
```diff
@@ -27,9 +27,18 @@ void HexagonGame::update(ssvu::FT mFT)
...
+
+    if (timeTillUpdate <= 0)
```
Comment (SuperV1234) [inline src/SSVOpenHexagon/Core/HGUpdate.cpp:35]:
```suggestion
    if (timeTillUpdate <= 0.f)
```

File: src/SSVOpenHexagon/Core/HGUpdate.cpp [hunk 5]
```diff
@@ -27,9 +27,18 @@ void HexagonGame::update(ssvu::FT mFT)
...
+    {
+        // only required for Steam
+        steamManager.set_rich_presence_in_game(levelData->name, status.getTimeSeconds());
+        steamManager.run_callbacks();
+        timeTillUpdate = DELAY_TO_UPDATE;
+    }
 
     discordManager.set_rich_presence_in_game(
```
Comment (SuperV1234) [inline src/SSVOpenHexagon/Core/HGUpdate.cpp:43]: Doesn't Discord need the same treatment?

Comment (AlphaPromethium) [reply src/SSVOpenHexagon/Core/HGUpdate.cpp:43]: Had a quick check by watching someone else play, and it does appear so. I will apply the same thing to discord and update the card/PR's description.

**Comment by AlphaPromethium** [comment]
Discord now has the same treatment as it is also experiencing the same issue.

File: include/SSVOpenHexagon/Core/HexagonGame.hpp [hunk 6]
```diff
@@ -59,6 +59,7 @@ class HexagonGame
     CPlayer player;
     std::vector<CWall> walls;
     CCustomWallManager cwManager;
+    float timeUntilRichPresenceUpdate;
```
Comment (SuperV1234) [inline include/SSVOpenHexagon/Core/HexagonGame.hpp:62]:
```suggestion
    float timeUntilRichPresenceUpdate = 0.f;
```

File: src/SSVOpenHexagon/Core/HGUpdate.cpp [hunk 7]
```diff
@@ -51,15 +51,22 @@ void HexagonGame::update(ssvu::FT mFT)
...
+
     // Presence formatter
-    const std::string presenceStr =
-        nameStr + " [x" + diffStr + "] - " + timeStr + "s";
+    const std::string presenceStr = nameStr + " [x" + diffStr + "] - " + timeStr + "s";
+
+    if (timeUntilRichPresenceUpdate <= 0.f)
+    {
+        steamManager.set_rich_presence_in_game(nameStr, diffStr, timeStr);
+        steamManager.run_callbacks();
```
Comment (SuperV1234) [inline src/SSVOpenHexagon/Core/HGUpdate.cpp:63]: `run_callbacks()` should be executed per frame, both here and for `discordManager`
